---
# tasks file for ansible-role-xdmod
#
 - name: install mysql-python
   yum: name=MySQL-python state=present

# - name: tune database ToDo: Fix this
#   template: src=my.cnf.j2 dest=/etc/my.cnf.d/tune.cnf

 - name: Ensure MySQL is started and enabled on boot.
   service: 
     name=mariadb 
     state=started 
     enabled=true

 - name: template in my.conf
   template: src=my.cnf.j2 dest=/etc/my.cnf backup=yes

 - name: Create databases
   mysql_db: name={{ item }}
   with_items: "{{xdmod_databases }}"
