---
# tasks file for ansible-role-xdmod
#
 - name: install mysql-python
   yum: name=MySQL-python state=present

# - name: tune database ToDo: Fix this
#   template: src=my.cnf.j2 dest=/etc/my.cnf.d/tune.cnf

 - name: template in my.cnf
   template: src=my.cnf.j2 dest=/etc/my.cnf backup=yes
   register: xdmod_mysql_conf_reg

 - name: create mysqldb datadir
   file: path={{ xdmod_dbdir }} state=directory owner=mysql group=mysql mode=0755

 - name: Ensure MySQL is started and enabled on boot.
   service: 
     name=mariadb 
     state=started 
     enabled=true

 - name: restart mysql if my.conf has been updated
   service: 
     name=mariadb 
     state=restarted 

 - name: Create databases
   mysql_db: name={{ item }}
   with_items: "{{xdmod_databases }}"
