---
# tasks file for ansible-role-xdmod
#

# echo date.timezone = Europe/Helsinki >> /etc/php.ini
#
 - name: set php timezone
   lineinfile: dest=/etc/php.ini 
               regexp='^date.timezone = {{ xdmod_php_timezone }}$' 
               line="date.timezone = {{ xdmod_php_timezone }}" 
               state=present
