---
# tasks file for ansible-role-xdmod
#

# echo date.timezone = Europe/Helsinki >> /etc/php.ini
#
 - name: set php timezone
   lineinfile: dest=/etc/php.ini 
                regexp='^date.timezone = Europe/Helsinki$'' 
                line="date.timezone = Europe/Helsinki" 
                state=present
