---

# source installation
# http://xdmod.sourceforge.net/install-source.html

 - name: download xdmod tar ball
   get_url: url="http://downloads.sourceforge.net/project/xdmod/xdmod/5.0.0/xdmod-5.0.0.tar.gz" dest=/opt/xdmod-5.0.0.tar.gz
   when: xdmod_tarball_install

 - name: extract said tar ball xdmod
   unarchive: src=/opt/xdmod-5.0.0.tar.gz dest=/opt/ copy=no
   when: xdmod_tarball_install

 - name: run the install script
   command: ./install --prefix=/opt/xdmod
   args:
     chdir: /opt/xdmod-5.0.0
     creates: /opt/xdmod
   when: xdmod_tarball_install

 # /opt/xdmod/bin/xdmod-setup
 #
 
 - name: symlink config files for apache cron logrotate
   file: src={{ item.src }} dest={{ item.dest }} state=link
   with_items: xdmod_symlinks

 - name: start and enable httpd
   service: name=httpd state=started enabled=yes
#

# Uncomment the line below if running Apache 2.4:
#                #Require all granted
#
 - name: require all granted in the httpd config
   lineinfile: dest=/etc/httpd/conf.d/xdmod.conf
               regexp='#Require all granted$'
               line="Require all granted"
               state=present
   notify:
    - restart httpd

#
 - name: is port 8080 up yet
   wait_for: port=8080 timeout=60 host=localhost
