---

# source installation
# http://xdmod.sourceforge.net/install-source.html

 - name: download xdmod tar ball
   get_url: url="http://downloads.sourceforge.net/project/xdmod/xdmod/5.0.0/xdmod-5.0.0.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fxdmod%2Ffiles%2Fxdmod%2F5.0.0%2F&ts=1450090065&use_mirror=vorboss" dest=/opt/xdmod-5.0.0.tar.gz
   when: xdmod_tarball_install

 - name: extract said tar ball xdmod
   unarchive: src=/opt/xdmod-5.0.0.tar.gz dest=/opt/
   when: xdmod_tarball_install

 - name: symlink /opt/xdmod-version to /opt/xdmod
   file: src=/opt/xdmod-5.0.0 dest=/opt/xdmod state=link
   when: xdmod_tarball_install

 # /opt/xdmod/bin/xdmod-setup
 #
 
 - name: symlink config files for apache cron logrotate
   file: src={{ item.src }} dest={{ item.dest }} state=link
   with_items: xdmod_symlinks

# need to configure xdmod more before this will work
# - name: restart httpd
#   service: name=httpd state=restarted
#
# - name: is port 8080 up yet
#   wait_for: port=8080 timeout=60 host=localhost
