---

 - name: download xdmod tar ball
   get_url: url="http://downloads.sourceforge.net/project/xdmod/xdmod/5.0.0/xdmod-5.0.0.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fxdmod%2Ffiles%2Fxdmod%2F5.0.0%2F&ts=1450090065&use_mirror=vorboss" dest=/opt/xdmod-5.0.0.tar.gz

